### ISSUE TITLE
jemu-decoder/web/common/components下no such file报错

### ISSUE THREAD

**Issue by x402** [ysyx-org/jemu-decoder#11]
git submodule初始化好之后在./web下`npm run dev`，会报一个no such file or dictionary的错，具体要找的文件是badge.vue和button.vue，这两个文件在components目录下都是大写开头的（即Badge.vue和Button.vue），若把这两个文件改为小写开头则`npm run dev`可以运行成功，正常显示网页。
现在我已无法复现这个报错，如果把文件改回大写开头，`npm run dev`也能运行但是会出现空白网页。

**Comment by zhangyx1998** [comment]
问题已经定位
