### ISSUE TITLE
描述规范的建议：load/store的描述

### ISSUE THREAD

**Issue by x402** [ysyx-org/jemu-decoder#12]
访存可以用`M(addr)`表示，比`$`更直观。同样用切片表示取addr为起始地址处的多少个位，而不用mask表示，因为mask并不是程序状态变量，写进状态转移里显得意义不明。
## load
```
# lb
exec:
  rd: "SEXT(M(rs1 + imm)[7:0])"
```

表示以addr=rs1+imm为起始地址取8个bit（1byte）并进行符号扩展
![lb](https://user-images.githubusercontent.com/75256484/180380826-f993654c-efca-413b-bf4b-b062f3ca00e4.png)

---

```
# lhu
exec:
  rd: "M(rs1 + imm)[15:0]"
```
表示以addr=rs1+imm为起始地址取16个bit（2byte），没有SEXT则默认为零扩展
![lhu](https://user-images.githubusercontent.com/75256484/180380837-2ea87891-83b1-44a0-844f-4f0a3696c9c3.png)

## store
```
# sb
exec:
  M(rs1 + imm)[7:0]: "rs2[7:0]"
```
表示取rs2的低8位存入内存以addr=rs1+imm为起始地址的低8bit（1byte）
![sb](https://user-images.githubusercontent.com/75256484/180380854-49eb8d3a-198b-4c0c-8357-f3c7e45e14d6.png)

**Comment by zhangyx1998** [comment]
这是个不错的建议，你可以把它写成PR
