### ISSUE TITLE
本地构建时提示缺少文件

### ISSUE THREAD

**Issue by x402** [ysyx-org/jemu-decoder#9]
自己修改了一些指令描述的时候想看看网页效果，但是不知道怎么运行
![QQ图片20220713203831](https://user-images.githubusercontent.com/75256484/178735505-4d23dd88-5b4b-4e93-928c-fa7520cccc02.png)

**Comment by zhangyx1998** [comment]
需要在 jemu-decoder 目录（项目根目录下）先运行 `npm run build` , 然后再进入 web 目录运行 `npm run dev` 查看效果

**Comment by x402** [comment]
> 需要在 jemu-decoder 目录（项目根目录下）先运行 `npm run build` , 然后再进入 web 目录运行 `npm run dev` 查看效果

谢谢！

**Comment by x402** [comment]
在README里有，没留意看不好意思（捂脸）

**Comment by zhangyx1998** [comment]
> 在README里有，没留意看不好意思（捂脸）

我是刚刚回答完你的 issue 之后才加上去的，不是你的锅
